theme: jekyll-theme-hacker
title: slinkous
description: A website.

show_downloads: "false"
# google_analytics: [Your Google Analytics tracking ID]
github:
  zip_url: https://github.com/slinkouswasalreadytaken/slinkouswasalreadytaken.github.io/archive/master.zip
  another_url: https://www.planetminecraft.com/texture-pack/void-texturepack-labpbr-procedural-texturepack-slinkous/
